name: All-Time Language Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch: 
  push: {branches: ["master", "main"]}
  

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: CosmicDev404
          template: classic
          base: "" 
          committer_token: ${{ secrets.METRICS_TOKEN }} 
          output_action: commit
          committer_branch: main

          # --- All-Time Languages Configuration ---
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_sections: most-used
          plugin_languages_limit: 20
          repositories: all
          plugin_languages_recent_days: 0
          plugin_languages_recent_load: 0
          repositories_batch: 100
          plugin_languages_ignored: html
          plugin_languages_categories: programming, data, markup
          commits_authoring: CosmicDev404, agrim.sharma0007@gmail.com
          plugin_languages_threshold: 0%

          
          # Timezone
          config_timezone: Asia/Kolkata
