name: All-Time Language Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch: 
  push: {branches: ["master", "main"]}
  

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: CosmicDev404
          template: repository
          base: "" 
          committer_token: ${{ secrets.METRICS_TOKEN }} 
          output_action: commit
          committer_branch: main

          plugin_languages: yes
          plugin_languages_indepth: false
          plugin_languages_sections: most-used
          plugin_languages_limit: 20
          plugin_languages_details: bytes, lines, percentage
          plugin_languages_ignored: html, css, markdown
          plugin_languages_threshold: 0%


          
          # Timezone
          config_timezone: Asia/Kolkata
